<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>UrlInsight.Core</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AngleSharp" Version="1.8.3" />
    <PackageReference Include="SmartReader" Version="0.11.1" />
    <PackageReference Include="PdfPig" Version="0.1.16" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="8.0.31" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="UrlInsight.Core.Tests" />
  </ItemGroup>

</Project>
